// <auto-generated />
using MarvelRivals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarvelRivalsApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.Property<int?>("AdditionalFieldsId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCollab")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalFieldsId");

                    b.HasIndex("HeroId");

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.AdditionalFields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Casting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnergyCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialEffect")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdditionalFields");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.Costume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Appearance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostumeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("Costume");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.GameMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameMapId")
                        .HasColumnType("int");

                    b.Property<string>("GameMode")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompetitive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubMapId")
                        .HasColumnType("int");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubMapId");

                    b.ToTable("GameMaps");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.Hero", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttackType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.MatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameModeId")
                        .HasColumnType("int");

                    b.Property<string>("MapThumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchMapId")
                        .HasColumnType("int");

                    b.Property<string>("MatchMapName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MatchPlayDuration")
                        .HasColumnType("float");

                    b.Property<int>("MatchPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("MatchPlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchPlayerUid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchSeason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MatchTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("MatchUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchWinnerSide")
                        .HasColumnType("int");

                    b.Property<int>("MvpUid")
                        .HasColumnType("int");

                    b.Property<int>("PlayModeId")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreInfoId")
                        .HasColumnType("int");

                    b.Property<int>("SvpUid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchPlayerId");

                    b.HasIndex("ScoreInfoId");

                    b.ToTable("MatchHistory");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("Camp")
                        .HasColumnType("int");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<bool>("Disconnected")
                        .HasColumnType("bit");

                    b.Property<int>("IsWinId")
                        .HasColumnType("int");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<int>("PlayerHeroId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerUid")
                        .HasColumnType("int");

                    b.Property<int>("ScoreInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsWinId");

                    b.HasIndex("PlayerHeroId");

                    b.HasIndex("ScoreInfoId");

                    b.ToTable("MatchPlayer");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.PlayerHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("Deaths")
                        .HasColumnType("int");

                    b.Property<int?>("HeroId")
                        .HasColumnType("int");

                    b.Property<string>("HeroName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Kills")
                        .HasColumnType("int");

                    b.Property<double?>("PlayTime")
                        .HasColumnType("float");

                    b.Property<double?>("TotalDamageTaken")
                        .HasColumnType("float");

                    b.Property<double?>("TotalHeroDamage")
                        .HasColumnType("float");

                    b.Property<double?>("TotalHeroHeal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PlayerHero");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.PlayerScoreInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AddScore")
                        .HasColumnType("float");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("NewLevel")
                        .HasColumnType("int");

                    b.Property<double?>("NewScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PlayerScoreInfo");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.ScoreInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("One")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "1");

                    b.Property<int>("Zero")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "0");

                    b.HasKey("Id");

                    b.ToTable("ScoreInfo");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.SubMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubMapId")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubMap");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.Transformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Health")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovementSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransformationsId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("Transformation");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.WinInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WinInfo");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.Ability", b =>
                {
                    b.HasOne("MarvelRivalsApi.Models.Entities.AdditionalFields", "AdditionalFields")
                        .WithMany()
                        .HasForeignKey("AdditionalFieldsId");

                    b.HasOne("MarvelRivalsApi.Models.Entities.Hero", null)
                        .WithMany("Abilities")
                        .HasForeignKey("HeroId");

                    b.Navigation("AdditionalFields");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.Costume", b =>
                {
                    b.HasOne("MarvelRivalsApi.Models.Entities.Hero", null)
                        .WithMany("Costumes")
                        .HasForeignKey("HeroId");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.GameMap", b =>
                {
                    b.HasOne("MarvelRivalsApi.Models.Entities.SubMap", "SubMap")
                        .WithMany()
                        .HasForeignKey("SubMapId");

                    b.Navigation("SubMap");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.MatchHistory", b =>
                {
                    b.HasOne("MarvelRivalsApi.Models.Entities.MatchPlayer", "MatchPlayer")
                        .WithMany()
                        .HasForeignKey("MatchPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarvelRivalsApi.Models.Entities.ScoreInfo", "ScoreInfo")
                        .WithMany()
                        .HasForeignKey("ScoreInfoId");

                    b.Navigation("MatchPlayer");

                    b.Navigation("ScoreInfo");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.MatchPlayer", b =>
                {
                    b.HasOne("MarvelRivalsApi.Models.Entities.WinInfo", "IsWin")
                        .WithMany()
                        .HasForeignKey("IsWinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarvelRivalsApi.Models.Entities.PlayerHero", "PlayerHero")
                        .WithMany()
                        .HasForeignKey("PlayerHeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarvelRivalsApi.Models.Entities.PlayerScoreInfo", "ScoreInfo")
                        .WithMany()
                        .HasForeignKey("ScoreInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IsWin");

                    b.Navigation("PlayerHero");

                    b.Navigation("ScoreInfo");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.Transformation", b =>
                {
                    b.HasOne("MarvelRivalsApi.Models.Entities.Hero", null)
                        .WithMany("Transformations")
                        .HasForeignKey("HeroId");
                });

            modelBuilder.Entity("MarvelRivalsApi.Models.Entities.Hero", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Costumes");

                    b.Navigation("Transformations");
                });
#pragma warning restore 612, 618
        }
    }
}
