// <auto-generated />
using MarvelRivalsApiAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarvelRivalsApiAPI.Migrations
{
    [DbContext(typeof(MarvelRivalsDBContext))]
    [Migration("20250712084025_AddMarvelRivalsChanges2")]
    partial class AddMarvelRivalsChanges2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.IsWinInfo", b =>
                {
                    b.Property<int>("IsWinInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IsWinInfoId"));

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("IsWinInfoId");

                    b.ToTable("IsWinInfo");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.MatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameModeId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "game_mode_id");

                    b.Property<string>("MapThumbnail")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "map_thumbnail");

                    b.Property<int>("MatchMapId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "match_map_id");

                    b.Property<string>("MatchMapName")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "match_map_name");

                    b.Property<double>("MatchPlayDuration")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "match_play_duration");

                    b.Property<int>("MatchPlayerPlayerUid")
                        .HasColumnType("int");

                    b.Property<string>("MatchSeason")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "match_season");

                    b.Property<long>("MatchTimeStamp")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "match_timestamp");

                    b.Property<string>("MatchUid")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "match_uid");

                    b.Property<int>("MatchWinnerSide")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "match_winner_side");

                    b.Property<int>("MvpUid")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "mvp_uid");

                    b.Property<int>("PlayModeId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "play_mode_id");

                    b.Property<int>("SvpUid")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "svp_uid");

                    b.HasKey("Id");

                    b.HasIndex("MatchPlayerPlayerUid");

                    b.ToTable("MatchHistory");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.MatchPlayer", b =>
                {
                    b.Property<int>("PlayerUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "player_uid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerUid"));

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("Camp")
                        .HasColumnType("int");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<bool>("Disconnected")
                        .HasColumnType("bit");

                    b.Property<int>("IsWinId")
                        .HasColumnType("int");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<int>("PlayerHeroId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScoreInfoId")
                        .HasColumnType("int");

                    b.HasKey("PlayerUid");

                    b.HasIndex("IsWinId");

                    b.HasIndex("PlayerHeroId");

                    b.HasIndex("ScoreInfoId");

                    b.ToTable("MatchPlayer");

                    b.HasAnnotation("Relational:JsonPropertyName", "match_player");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.PlayTime", b =>
                {
                    b.Property<int>("PlayTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayTimeId"));

                    b.Property<string>("formatted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("raw")
                        .HasColumnType("int");

                    b.HasKey("PlayTimeId");

                    b.ToTable("PlayTime");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.PlayerHero", b =>
                {
                    b.Property<int>("HeroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeroId"));

                    b.Property<string>("Assists")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deaths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayTimeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalDamageTaken")
                        .HasColumnType("int");

                    b.Property<int>("TotalHeroDamage")
                        .HasColumnType("int");

                    b.Property<int>("TotalHeroHeal")
                        .HasColumnType("int");

                    b.HasKey("HeroId");

                    b.HasIndex("PlayTimeId");

                    b.ToTable("PlayerHero");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.PlayerScoreInfo", b =>
                {
                    b.Property<int>("PlayerScoreInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerScoreInfoId"));

                    b.Property<int>("addScore")
                        .HasColumnType("int");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.Property<int>("newLevel")
                        .HasColumnType("int");

                    b.Property<int>("newScore")
                        .HasColumnType("int");

                    b.HasKey("PlayerScoreInfoId");

                    b.ToTable("PlayerScoreInfo");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.MatchHistory", b =>
                {
                    b.HasOne("MarvelRivalsApiAPI.Data.MatchPlayer", "MatchPlayer")
                        .WithMany()
                        .HasForeignKey("MatchPlayerPlayerUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchPlayer");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.MatchPlayer", b =>
                {
                    b.HasOne("MarvelRivalsApiAPI.Data.IsWinInfo", "IsWin")
                        .WithMany()
                        .HasForeignKey("IsWinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarvelRivalsApiAPI.Data.PlayerHero", "PlayerHero")
                        .WithMany()
                        .HasForeignKey("PlayerHeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarvelRivalsApiAPI.Data.PlayerScoreInfo", "ScoreInfo")
                        .WithMany()
                        .HasForeignKey("ScoreInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IsWin");

                    b.Navigation("PlayerHero");

                    b.Navigation("ScoreInfo");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.PlayerHero", b =>
                {
                    b.HasOne("MarvelRivalsApiAPI.Data.PlayTime", "PlayTime")
                        .WithMany()
                        .HasForeignKey("PlayTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayTime");
                });
#pragma warning restore 612, 618
        }
    }
}
