// <auto-generated />
using MarvelRivalsApiAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarvelRivalsApiAPI.Migrations
{
    [DbContext(typeof(MarvelRivalsDBContext))]
    [Migration("20250714114928_AddIdToMatchDetail3")]
    partial class AddIdToMatchDetail3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Badge", b =>
                {
                    b.Property<int>("BadgesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgesId"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "count");

                    b.Property<int?>("MatchDetailsPlayersId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("BadgesId");

                    b.HasIndex("MatchDetailsPlayersId");

                    b.ToTable("Badge");

                    b.HasAnnotation("Relational:JsonPropertyName", "badges");
                });

            modelBuilder.Entity("GameMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameModeId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "game_mode_id");

                    b.Property<string>("GameModeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "game_mode_name");

                    b.HasKey("Id");

                    b.ToTable("GameMode");

                    b.HasAnnotation("Relational:JsonPropertyName", "game_mode");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.IsWinInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "is_win");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "score");

                    b.HasKey("id");

                    b.ToTable("IsWinInfo");

                    b.HasAnnotation("Relational:JsonPropertyName", "is_win");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.MatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameModeId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "game_mode_id");

                    b.Property<string>("MapThumbnail")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "map_thumbnail");

                    b.Property<int>("MatchMapId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "match_map_id");

                    b.Property<string>("MatchMapName")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "match_map_name");

                    b.Property<double>("MatchPlayDuration")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "match_play_duration");

                    b.Property<int>("MatchPlayerid")
                        .HasColumnType("int");

                    b.Property<string>("MatchSeason")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "match_season");

                    b.Property<long>("MatchTimeStamp")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "match_time_stamp");

                    b.Property<string>("MatchUid")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "match_uid");

                    b.Property<int>("MatchWinnerSide")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "match_winner_side");

                    b.Property<int>("MvpUid")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "mvp_uid");

                    b.Property<int>("PlayModeId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "play_mode_id");

                    b.Property<int?>("ScoreInfoId")
                        .HasColumnType("int");

                    b.Property<int>("SvpUid")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "svp_uid");

                    b.HasKey("Id");

                    b.HasIndex("MatchPlayerid");

                    b.HasIndex("ScoreInfoId");

                    b.ToTable("MatchHistory");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.MatchPlayer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Assists")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "assists");

                    b.Property<int?>("Camp")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "camp");

                    b.Property<int>("Deaths")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "deaths");

                    b.Property<bool>("Disconnected")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "disconnected");

                    b.Property<int>("IsWinId")
                        .HasColumnType("int");

                    b.Property<int>("Kills")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "kills");

                    b.Property<int?>("PlayerHeroId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerUid")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "player_uid");

                    b.Property<int?>("ScoreInfoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("IsWinId");

                    b.HasIndex("PlayerHeroId");

                    b.HasIndex("ScoreInfoid");

                    b.ToTable("MatchPlayer");

                    b.HasAnnotation("Relational:JsonPropertyName", "match_player");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.PlayerHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "assists");

                    b.Property<int>("Deaths")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "deaths");

                    b.Property<int>("HeroId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "hero_id");

                    b.Property<string>("HeroName")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "hero_name");

                    b.Property<string>("HeroType")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "hero_type");

                    b.Property<int>("Kills")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "kills");

                    b.Property<int?>("MatchDetailsPlayersId")
                        .HasColumnType("int");

                    b.Property<double>("PlayTimeId")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "play_time");

                    b.Property<double>("TotalDamageTaken")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "total_damage_taken");

                    b.Property<double>("TotalHeroDamage")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "total_hero_damage");

                    b.Property<int>("TotalHeroHeal")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "total_hero_heal");

                    b.HasKey("Id");

                    b.HasIndex("MatchDetailsPlayersId");

                    b.ToTable("PlayerHero");

                    b.HasAnnotation("Relational:JsonPropertyName", "player_heroes");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.PlayerScoreInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double?>("addScore")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "add_score");

                    b.Property<int?>("level")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "level");

                    b.Property<int?>("newLevel")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "new_level");

                    b.Property<double?>("newScore")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "new_score");

                    b.HasKey("id");

                    b.ToTable("PlayerScoreInfo");

                    b.HasAnnotation("Relational:JsonPropertyName", "score_info");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.ScoreInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Lose")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "0");

                    b.Property<int>("Win")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "1");

                    b.HasKey("Id");

                    b.ToTable("ScoreInfo");

                    b.HasAnnotation("Relational:JsonPropertyName", "score_info");
                });

            modelBuilder.Entity("MatchDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameModeId")
                        .HasColumnType("int");

                    b.Property<string>("MatchUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "match_uid");

                    b.Property<int>("MvpHeroId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "mvp_hero_id");

                    b.Property<long>("MvpUid")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "mvp_uid");

                    b.Property<string>("ReplayId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "replay_id");

                    b.Property<int>("SvpHeroId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "svp_hero_id");

                    b.Property<long>("SvpUid")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "svp_uid");

                    b.HasKey("Id");

                    b.HasIndex("GameModeId");

                    b.ToTable("MatchDetail");
                });

            modelBuilder.Entity("MatchDetailsPlayers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "assists");

                    b.Property<int>("Camp")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "camp");

                    b.Property<string>("CurHeroIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "cur_hero_icon");

                    b.Property<int>("CurHeroId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "cur_hero_id");

                    b.Property<int>("Deaths")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "deaths");

                    b.Property<int>("IsWin")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "is_win");

                    b.Property<int>("Kills")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "kills");

                    b.Property<int?>("MatchDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "nick_name");

                    b.Property<long>("PlayerIcon")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "player_icon");

                    b.Property<long>("PlayerUid")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "player_uid");

                    b.Property<double>("TotalDamageTaken")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "total_damage_taken");

                    b.Property<double>("TotalHeroDamage")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "total_hero_damage");

                    b.Property<double>("TotalHeroHeal")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "total_hero_heal");

                    b.HasKey("Id");

                    b.HasIndex("MatchDetailsId");

                    b.ToTable("MatchDetailsPlayers");

                    b.HasAnnotation("Relational:JsonPropertyName", "match_players");
                });

            modelBuilder.Entity("Badge", b =>
                {
                    b.HasOne("MatchDetailsPlayers", null)
                        .WithMany("Badges")
                        .HasForeignKey("MatchDetailsPlayersId");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.MatchHistory", b =>
                {
                    b.HasOne("MarvelRivalsApiAPI.Data.MatchPlayer", "MatchPlayer")
                        .WithMany()
                        .HasForeignKey("MatchPlayerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarvelRivalsApiAPI.Data.ScoreInfo", "ScoreInfo")
                        .WithMany()
                        .HasForeignKey("ScoreInfoId");

                    b.Navigation("MatchPlayer");

                    b.Navigation("ScoreInfo");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.MatchPlayer", b =>
                {
                    b.HasOne("MarvelRivalsApiAPI.Data.IsWinInfo", "IsWin")
                        .WithMany()
                        .HasForeignKey("IsWinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarvelRivalsApiAPI.Data.PlayerHero", "PlayerHero")
                        .WithMany()
                        .HasForeignKey("PlayerHeroId");

                    b.HasOne("MarvelRivalsApiAPI.Data.PlayerScoreInfo", "ScoreInfo")
                        .WithMany()
                        .HasForeignKey("ScoreInfoid");

                    b.Navigation("IsWin");

                    b.Navigation("PlayerHero");

                    b.Navigation("ScoreInfo");
                });

            modelBuilder.Entity("MarvelRivalsApiAPI.Data.PlayerHero", b =>
                {
                    b.HasOne("MatchDetailsPlayers", null)
                        .WithMany("PlayerHeroes")
                        .HasForeignKey("MatchDetailsPlayersId");
                });

            modelBuilder.Entity("MatchDetails", b =>
                {
                    b.HasOne("GameMode", "GameMode")
                        .WithMany()
                        .HasForeignKey("GameModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameMode");
                });

            modelBuilder.Entity("MatchDetailsPlayers", b =>
                {
                    b.HasOne("MatchDetails", null)
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchDetailsId");
                });

            modelBuilder.Entity("MatchDetails", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("MatchDetailsPlayers", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("PlayerHeroes");
                });
#pragma warning restore 612, 618
        }
    }
}
